spring.application.name=finanzas-backend
spring.data.mongodb.uri=mongodb://admin:prueba1234@localhost:27017/finanzas?authSource=admin
security.jwt.secret-key=${JWT_SECRET:c3VwZXItc2VjcmV0YS1wYXJhLWp3dC0zMi1ieXRlcy1taW4=}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
